### ISSUE TITLE
Allow dynamic BreadcrumbItem

### ISSUE THREAD

**Issue by DjLeChuck** [umanit/seo-bundle#15]
For example, when dealing with a tree of categories how can we build the whole path, one item per category?

Actually, the `Breadcrumb` annotation takes a finish list of `BreadcrumbItem` so it's impossible.

I have two ideas for the moment:
* Add a new `BreadcrumbDynamicItem` which returns a list of `BreadcrumbItem`
* An event or whatever else in `BreadcrumbBuilder` to deal with others `PropertyAccessorInterface` exceptions and ignore them if needed

Any other suggestions?

**Comment by artggd** [comment]
It could be made possible by allowing the `value` of the `Breadcrumb` annotation to accept either a list of `BreadcrumbItem` (as it is now), or a service id. Close to what `SchemaOrgBuilder` annotation does.

The service would have to implement en interface, having a method that would return a list of `BreadcrumbItem`.

**Comment by DjLeChuck** [comment]
Done on the `develop version`
